package:
  name: gmpy2
  version: 2.0.0

source:
  fn: gmpy2-2.0.0.zip
  url: https://gmpy.googlecode.com/files/gmpy2-2.0.0.zip

requirements:
  build:
    - gmp
    - mpfr
    - mpc
    - python
  run:
    - gmp
    - mpfr
    - mpc
    - python

about:
  home: https://code.google.com/p/gmpy/
  license: LGPL
