
package:
    name: wxpython
    version: 3.0.0.0

source:
    fn: wxPython-src-3.0.0.0.tar.bz2
    url: http://downloads.sourceforge.net/wxpython/wxPython-src-3.0.0.0.tar.bz2

build:
    number: 0

requirements:
    build:
        - python
        - distribute

    run:
        - python

test:
    imports:
        - wx

about:
    home: http://www.wxpython.org
    license: wxWindows Licese

