package:
  name: qt
  version: 4.8.5

source:
  fn: qt-everywhere-opensource-src-4.8.5.tar.gz
  url: http://download.qt-project.org/official_releases/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.tar.gz
  md5: 1864987bdbb2f58f8ae8b350dfdbe133
  patches:
    - acceptance.patch
    - 10.5.patch [osx]

requirements:
  build:
    - freetype

about:
    home: http://qt-project.org
    license: LGPL
